version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: api
    depends_on:
      - db
    ports:
      - "4010:4010"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:password@db/mydatabase
    restart: always